export const products = [
    {
        id: 1,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-01.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "women's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 2,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-02.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "women's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 3,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-03.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "men's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 4,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-04.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "women's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 5,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-05.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "women's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 6,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-06.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "accessories",
        price: '$35',
        color: 'Black',
    },
    {
        id: 7,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-07.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "men's clothing",
        price: '$35',
        color: 'Black',
    },
    {
        id: 8,
        title: 'Basic Tee',
        href: '#',
        // imageSrc: 'https://tailwindui.com/plus/img/ecommerce-images/product-page-01-related-product-01.jpg',
        image: './images/product-08.jpg',
        imageAlt: "Front of men's Basic Tee in black.",
        category: "women's clothing",
        price: '$35',
        color: 'Black',
    },
    // More products...
]