import React from 'react'
import HeroPages from '../components/HeroPages/HeroPages'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faEnvelope, faLocationDot, faPhoneFlip } from '@fortawesome/free-solid-svg-icons'

export const metadata = {
    title: "Store - Contact",
    description: "Generated by create next app and this is Contact page",
};

function Contact() {
    return (
        <>
            <HeroPages title={"Contact"} />
            <section className="pt-[104px] pb-[116px]">
                <div className="mx-auto px-4 sm:px-6 lg:px-8 max-w-2xl lg:max-w-7xl container">
                    <div className="flex lg:flex-row flex-col flex-wrap">
                        <div className="border-[#e6e6e6] border-[1px] px-[70px] lg:px-15 pt-[55px] pb-[70px] w-full lg:w-1/2">
                            <form>
                                <h4 className="pb-[30px] text-[#333] text-[24px] text-center leading-[1.5]">Send Us A Message</h4>

                                <div className="relative email">
                                    <input className="border-[#e6e6e6] border-[1px] pr-[30px] pl-[62px] w-full h-[50px] text-[#333] text-[13px] leading-[1.6923] plh3" type="text" name="email" placeholder="Your Email Address" />
                                    <FontAwesomeIcon icon={faEnvelope} className='top-[50%] left-[5%] absolute w-[15px] text-[15px] text-gray-400 translate-y-[-50%]' />
                                </div>

                                <div className="my-[30px]">
                                    <textarea className="border-[#e6e6e6] border-[1px] px-[28px] py-[25px] rounded-[2px]s w-full min-h-[199px] text-[#333] text-[13px] leading-[1.6923] plh3" name="msg" placeholder="How Can We Help?"></textarea>
                                </div>

                                <button className="flex justify-center items-center bg-[#222] hover:bg-primary px-[15px] rounded-[23px] w-full h-[46px] text-[15px] text-white uppercase leading-[1.466667] transition duration-[0.4s] cursor-pointer bor1 hov-btn3">
                                    Submit
                                </button>
                            </form>
                        </div>

                        <div className="flex flex-col flex-wrap justify-center border-[#e6e6e6] border-[1px] px-[40px] lg:px-[93px] py-[60px] lg:py-[30px] w-full lg:w-1/2">
                            <div className="flex flex-wrap pb-[42px] w-full">
                                <span className="w-[30px] lg:w-[60px] text-[#222] text-[18px] text-center">
                                    <FontAwesomeIcon icon={faLocationDot} className='w-[20px] font-[400] text-[20px]' />
                                </span>

                                <div className="pt-[2px]">
                                    <span className="text-[#333] text-[18px] leading-[1.222222]">
                                        Address
                                    </span>

                                    <p className="pt-[18px] max-w-[245px] text-[#888] text-[15px] leading-[1.666667]">
                                        Lorem ipsum dolor sit amet consectetur, adipisicing elit Facilis.
                                    </p>
                                </div>
                            </div>

                            <div className="flex flex-wrap pb-[42px] w-full">
                                <span className="w-[30px] lg:w-[60px] text-[#222] text-[18px] text-center">
                                    <FontAwesomeIcon icon={faPhoneFlip} className='w-[20px] font-[400] text-[20px]' />
                                </span>

                                <div className="pt-[2px]">
                                    <span className="text-[#333] text-[18px] leading-[1.222222]">
                                        Lets Talk
                                    </span>

                                    <p className="pt-[18px] max-w-[245px] text-[#888] text-[15px] leading-[1.666667]">
                                        +1 800 1236879
                                    </p>
                                </div>
                            </div>

                            <div className="flex flex-wrap pb-[42px] w-full">
                                <span className="w-[30px] lg:w-[60px] text-[#222] text-[18px] text-center">
                                    <FontAwesomeIcon icon={faEnvelope} className='w-[20px] font-[400] text-[20px]' />
                                </span>

                                <div className="pt-[2px]">
                                    <span className="text-[#333] text-[18px] leading-[1.222222]">
                                        Sale Support
                                    </span>

                                    <p className="pt-[18px] max-w-[245px] text-[#888] text-[15px] leading-[1.666667]">
                                        contact@example.com
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section >


            <div id="map">
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d61485.081100443924!2d32.58708290260776!3d15.601392933207746!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x168e8e20509ad751%3A0x978f790d66a13a75!2sSo%20sweet%20baby%20Boutique!5e0!3m2!1sar!2s!4v1732099118516!5m2!1sar!2s"
                    width="100%" height="390" style={{ border: 0 }} allowFullScreen="" loading="lazy" aria-hidden="false" referrerpolicy="no-referrer-when-downgrade"
                    tabIndex="0"></iframe>
            </div>
        </>
    )
}

export default Contact
